


all:	
	@echo "\n\033[32mTest 1\033[0m"
	python test_dffexporter.py
	@echo "\n\033[32mTest 2\033[0m"
	python test_configobject.py	
	@echo "\n\033[32mTest 3\033[0m"
	@make -C sequenceTest
	@echo "\n\033[32mTest 4\033[0m"
	python test_configparser.py
